version: '3.5'

services:
  app:
    container_name: hashem-app
    image: hashem-app
    depends_on:
     - main_db
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true

  main_db:
    container_name: hashem-db
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hashem_db
    volumes:
      - ./temp-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"