apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashem-app
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: hashem-app
          image: hashem/alef-test:latest
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              httpHeaders:
                 - name: Host
                   value: localhost
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              httpHeaders:
                 - name: Host
                   value: localhost
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 10
          imagePullPolicy: Always
          ports:
            - containerPort: 8080      
          resources:
            requests:
              memory: "300Mi"
              cpu: "200m"
          envFrom:
            - configMapRef:
                name: hashem-app-configmap
            - secretRef:
                name: hashem-app-secret
