apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hashem-ingress
  namespace: test
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: hashem.com
    http:
      paths:
      - path: /healthz
        pathType: Exact  
        backend:
          service:
            name: hashem-app
            port: 
              number: 80

